run_logged $MYARCHY_INSTALL/config/config.sh
run_logged $MYARCHY_INSTALL/config/theme.sh
run_logged $MYARCHY_INSTALL/config/branding.sh
run_logged $MYARCHY_INSTALL/config/git.sh
run_logged $MYARCHY_INSTALL/config/nvim.sh
run_logged $MYARCHY_INSTALL/config/gpg.sh
run_logged $MYARCHY_INSTALL/config/timezones.sh
run_logged $MYARCHY_INSTALL/config/ssh-flakiness.sh
run_logged $MYARCHY_INSTALL/config/detect-keyboard-layout.sh
run_logged $MYARCHY_INSTALL/config/xcompose.sh
run_logged $MYARCHY_INSTALL/config/mise-work.sh
run_logged $MYARCHY_INSTALL/config/fix-powerprofilesctl-shebang.sh
run_logged $MYARCHY_INSTALL/config/mimetypes.sh
run_logged $MYARCHY_INSTALL/config/localdb.sh
run_logged $MYARCHY_INSTALL/config/walker-elephant.sh
run_logged $MYARCHY_INSTALL/config/fast-shutdown.sh
run_logged $MYARCHY_INSTALL/config/terminal.sh
run_logged $MYARCHY_INSTALL/config/hardware/network.sh
run_logged $MYARCHY_INSTALL/config/hardware/set-wireless-regdom.sh
run_logged $MYARCHY_INSTALL/config/hardware/fix-fkeys.sh
run_logged $MYARCHY_INSTALL/config/hardware/bluetooth.sh
run_logged $MYARCHY_INSTALL/config/hardware/printer.sh
run_logged $MYARCHY_INSTALL/config/hardware/usb-autosuspend.sh
run_logged $MYARCHY_INSTALL/config/hardware/ignore-power-button.sh
run_logged $MYARCHY_INSTALL/config/hardware/nvidia.sh
run_logged $MYARCHY_INSTALL/config/hardware/fix-f13-amd-audio-input.sh
run_logged $MYARCHY_INSTALL/config/hardware/intel.sh
